
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class Game

    Public Property Id As Integer

    Public Property json As String



    Public Overridable Property Game_Players As ICollection(Of Game_Player) = New HashSet(Of Game_Player)


End Class
