'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DatabaseContainer
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DatabaseContainer")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Games() As DbSet(Of Game)
    Public Overridable Property Players() As DbSet(Of Player)
    Public Overridable Property Game_Player() As DbSet(Of Game_Player)

End Class
